<<<<<<< HEAD
import { DataField } from 'app/model/data-field.model';
import { GraphEnum, VisualizationEnum } from 'app/model/enum.model';
import { DataFieldFactory, DataTable } from './data-field.model';
import { EntityTypeEnum } from './enum.model';
import { GraphData } from './graph-data.model';
=======
import { DataField } from "app/model/data-field.model";
import { GraphEnum, VisualizationEnum } from "app/model/enum.model";
import { DataFieldFactory, DataTable } from "./data-field.model";
import { EntityTypeEnum } from "./enum.model";
import { GraphData } from "./graph-data.model";
>>>>>>> a947a94743ca0203655e535e63bac428d1227be3

/**
 * Represents The Graph Config
 */
export interface Graph {
  config: GraphConfig;
  data: GraphData;
}

export class GraphConfig {
  // TODO: Bad Bad Bad...  Need to fix this.
  public static database = "gbm";

<<<<<<< HEAD
    // TODO: Bad Bad Bad...  Need to fix this.
    public static database = 'gbm';

    dirtyFlag = 1;
    visualization: VisualizationEnum;
    entity: EntityTypeEnum;
    graph: GraphEnum;
    table: DataTable;
    label = '';
    enableCohorts = true;
    enableGenesets = true;
    enablePathways = false;
    enableSupplemental = true;
    enableLabel = true;
    enableColor = true;
    enableShape = true;

    patientSelect: Array<string> = [];
    patientFilter: Array<string> = [];
    sampleSelect: Array<string> = [];
    markerSelect: Array<string> = [];
    sampleFilter: Array<string> = [];

    cohortName = 'All Patients';
    markerName = 'Pathways in Cancer';
    pathwayName = 'integrated cancer pathway';
    pathwayUri = 'https://oncoscape.v3.sttrcancer.org/data/pathways/http___identifiers.org_panther.pathway_P02742.json.gz';

    // Default Genes Listed Are 'KEGG Pathways In Cancer'
    markerFilter: Array<string> = ['ABL1', 'AKT1', 'AKT2', 'AKT3', 'APC', 'APC2', 'APPL1', 'AR', 'ARAF', 'ARNT', 'ARNT2', 'AXIN1',
        'AXIN2', 'BAD', 'BAX', 'BCL2', 'BCL2L1', 'BCR', 'BID', 'BIRC2', 'BIRC3', 'BIRC5', 'BMP2', 'BMP4', 'BRAF', 'BRCA2', 'CASP3',
        'CASP8', 'CASP9', 'CBL', 'CBLB', 'CBLC', 'CCDC6', 'CCNA1', 'CCND1', 'CCNE1', 'CCNE2', 'CDC42', 'CDH1', 'CDK2', 'CDK4', 'CDK6',
        'CDKN1A', 'CDKN1B', 'CDKN2A', 'CDKN2B', 'CEBPA', 'CHUK', 'CKS1B', 'COL4A1', 'COL4A2', 'COL4A4', 'COL4A6', 'CREBBP', 'CRK', 'CRKL',
        'CSF1R', 'CSF2RA', 'CSF3R', 'CTBP1', 'CTBP2', 'CTNNA1', 'CTNNA2', 'CTNNA3', 'CTNNB1', 'CUL2', 'CYCS', 'DAPK1', 'DAPK2', 'DAPK3',
        'DCC', 'DVL1', 'DVL2', 'DVL3', 'E2F1', 'E2F2', 'E2F3', 'EGF', 'EGFR', 'EGLN1', 'EGLN2', 'EGLN3', 'EP300', 'EPAS1', 'ERBB2', 'ETS1',
        'FADD', 'FAS', 'FASLG', 'FGF1', 'FGF10', 'FGF11', 'FGF12', 'FGF13', 'FGF14', 'FGF16', 'FGF17', 'FGF18', 'FGF19', 'FGF2', 'FGF20',
        'FGF21', 'FGF22', 'FGF23', 'FGF3', 'FGF4', 'FGF5', 'FGF6', 'FGF7', 'FGF8', 'FGF9', 'FGFR1', 'FGFR2', 'FGFR3', 'FH', 'FIGF', 'FLT3',
        'FLT3LG', 'FN1', 'FOS', 'FOXO1', 'FZD1', 'FZD10', 'FZD2', 'FZD3', 'FZD4', 'FZD5', 'FZD6', 'FZD7', 'FZD8', 'FZD9', 'GLI1', 'GLI2',
        'GLI3', 'GRB2', 'GSK3B', 'GSTP1', 'HDAC1', 'HDAC2', 'HGF', 'HHIP', 'HIF1A', 'HRAS', 'HSP90AA1', 'HSP90AB1', 'HSP90B1', 'IGF1',
        'IGF1R', 'IKBKB', 'IKBKG', 'IL6', 'IL8', 'ITGA2', 'ITGA2B', 'ITGA3', 'ITGA6', 'ITGAV', 'ITGB1', 'JAK1', 'JUN', 'JUP', 'KIT',
        'KITLG', 'KLK3', 'KRAS', 'LAMA1', 'LAMA2', 'LAMA3', 'LAMA4', 'LAMA5', 'LAMB1', 'LAMB2', 'LAMB3', 'LAMB4', 'LAMC1', 'LAMC2', 'LAMC3',
        'LEF1', 'LOC652346', 'LOC652671', 'LOC652799', 'MAP2K1', 'MAP2K2', 'MAPK1', 'MAPK10', 'MAPK3', 'MAPK8', 'MAPK9', 'MAX', 'MDM2',
        'MECOM', 'MET', 'MITF', 'MLH1', 'MMP1', 'MMP2', 'MMP9', 'MSH2', 'MSH3', 'MSH6', 'MTOR', 'MYC', 'NCOA4', 'NFKB1', 'NFKB2', 'NFKBIA',
        'NKX3-1', 'NOS2', 'NRAS', 'NTRK1', 'PAX8', 'PDGFA', 'PDGFB', 'PDGFRA', 'PDGFRB', 'PGF', 'PIAS1', 'PIAS2', 'PIAS3', 'PIAS4',
        'PIK3CA', 'PIK3CB', 'PIK3CD', 'PIK3CG', 'PIK3R1', 'PIK3R2', 'PIK3R3', 'PIK3R5', 'PLCG1', 'PLCG2', 'PLD1', 'PML', 'PPARD', 'PPARG',
        'PRKCA', 'PRKCB', 'PRKCG', 'PTCH1', 'PTCH2', 'PTEN', 'PTGS2', 'PTK2', 'RAC1', 'RAC2', 'RAC3', 'RAD51', 'RAF1', 'RALA', 'RALB',
        'RALBP1', 'RALGDS', 'RARA', 'RARB', 'RASSF1', 'RASSF5', 'RB1', 'RBX1', 'RELA', 'RET', 'RHOA', 'RUNX1', 'RUNX1T1', 'RXRA', 'RXRB',
        'RXRG', 'SHH', 'SKP2', 'SLC2A1', 'SMAD2', 'SMAD3', 'SMAD4', 'SMO', 'SOS1', 'SOS2', 'SPI1', 'STAT1', 'STAT3', 'STAT5A', 'STAT5B',
        'STK36', 'STK4', 'SUFU', 'TCEB1', 'TCEB2', 'TCF7', 'TCF7L1', 'TCF7L2', 'TFG', 'TGFA', 'TGFB1', 'TGFB2', 'TGFB3', 'TGFBR1', 'TGFBR2',
        'TP53', 'TPM3', 'TPR', 'TRAF1', 'TRAF2', 'TRAF3', 'TRAF4', 'TRAF5', 'TRAF6', 'VEGFA', 'VEGFB', 'VEGFC', 'VHL', 'WNT1', 'WNT10A',
        'WNT10B', 'WNT11', 'WNT16', 'WNT2', 'WNT2B', 'WNT3', 'WNT3A', 'WNT4', 'WNT5A', 'WNT5B', 'WNT6', 'WNT7A', 'WNT7B', 'WNT8A',
        'WNT8B', 'WNT9A', 'WNT9B', 'XIAP', 'ZBTB16'];

    // pointColor: DataField = DataFieldFactory.getUndefined();
    // pointShape: DataField = DataFieldFactory.getUndefined();
    // pointSize: DataField = DataFieldFactory.getUndefined();
    pointIntersect: DataField = DataFieldFactory.getUndefined();
    database: string;

    constructor() {
        this.database = GraphConfig.database;
    }
=======
  dirtyFlag = 1;
  visualization: VisualizationEnum;
  entity: EntityTypeEnum;
  graph: GraphEnum;
  table: DataTable;
  label = "";
  enableCohorts = true;
  enableGenesets = true;
  enablePathways = false;
  enableSupplemental = true;
  enableLabel = true;
  enableColor = true;
  enableShape = true;
  enableSize = false;

  patientSelect: Array<string> = [];
  patientFilter: Array<string> = [];
  sampleSelect: Array<string> = [];
  markerSelect: Array<string> = [];
  sampleFilter: Array<string> = [];

  cohortName = "All Patients";
  markerName = "Pathways in Cancer";
  pathwayName = "integrated cancer pathway";
  pathwayUri = "https://oncoscape.v3.sttrcancer.org/data/pathways/http___identifiers.org_panther.pathway_P02742.json.gz";

  // Default Genes Listed Are 'KEGG Pathways In Cancer'
  markerFilter: Array<string> = [
    "ABCG2",
    "AHNAK2",
    "AKT1",
    "ARHGAP26",
    "ASNS",
    "ATP2B3",
    "BCL11A",
    "BCL2",
    "BCL6",
    "BCOR",
    "BMI1",
    "BRAF",
    "BRCA1",
    "BRD4",
    "CACNA1D",
    "CAMTA1",
    "CARD11",
    "CBLB",
    "CCND3",
    "CD44",
    "CDKN2C",
    "CIITA",
    "COL1A1",
    "CREBBP",
    "CUL1",
    "DAXX",
    "DDX5",
    "DMRTA1",
    "DNAH5",
    "DOCK5",
    "ECT2L",
    "EGFR",
    "ELN",
    "ERBB2",
    "ERCC5",
    "EZH2",
    "EZR",
    "FAM46C",
    "FBXW7",
    "FCRL4",
    "FGFR3",
    "FLG",
    "FLI1",
    "FLT3",
    "FOXA1",
    "GLI1",
    "HGF",
    "HMCN1",
    "HNRNPA2B1",
    "HOOK3",
    "HOXA9",
    "IDH1",
    "IGF1R",
    "IRF4",
    "IRS1",
    "KCNJ5",
    "KDM5A",
    "KDR",
    "KEL",
    "KIT",
    "KLF4",
    "KMT2C",
    "KMT2D",
    "LDLR",
    "LPA",
    "LPP",
    "LRP2",
    "MALT1",
    "MAX",
    "MDM2",
    "MECOM",
    "MED12",
    "MLIP",
    "MLLT4",
    "MLLT6",
    "MSH6",
    "MTOR",
    "MUC16",
    "MUC17",
    "MYB",
    "MYH11",
    "MYH9",
    "NF1",
    "NIN",
    "NLRP2",
    "NOTCH2",
    "NTRK1",
    "OBSCN",
    "OLIG2",
    "OR4K5",
    "OR4Q3",
    "PAX3",
    "PAX5",
    "PCLO",
    "PCM1",
    "PDE4DIP",
    "PDGFRA",
    "PDGFRB",
    "PDPR",
    "PICALM",
    "PIK3C2G",
    "PIK3CA",
    "PIK3CB",
    "PIK3CG",
    "PIK3R1",
    "PIK3R2",
    "PIM1",
    "PKHD1",
    "PMS1",
    "PRKCD",
    "PRKCQ",
    "PTCH1",
    "PTEN",
    "PTPN11",
    "PTPRC",
    "RABEP1",
    "RANBP17",
    "RB1",
    "RPL10",
    "RPL22",
    "RPL5",
    "RYR2",
    "RYR3",
    "SDC4",
    "SETBP1",
    "SETD2",
    "SF3B1",
    "SHH",
    "SIRPB1",
    "SLC34A2",
    "SLC45A3",
    "SPTA1",
    "SREBF2",
    "SRSF2",
    "SS18",
    "STAG2",
    "TCF12",
    "TCHH",
    "TET2",
    "TMPRSS2",
    "TP53",
    "TPM3",
    "TRIM24",
    "TRRAP",
    "TTN",
    "UBR5",
    "USH2A",
    "USP6",
    "VOPP1",
    "VSTM2A",
    "WIF1",
    "ZNF521",
    "ZRSR2",
    "ABCA1",
    "ABI1",
    "ABL1",
    "AFF3",
    "AGAP2",
    "AKAP9",
    "AKT1S1",
    "AKT2",
    "AKT3",
    "ALK",
    "ARHGEF12",
    "ARPC1A",
    "ASPSCR1",
    "ATF1",
    "ATM",
    "ATRX",
    "BAGE",
    "BAGE2",
    "BAGE3",
    "BAGE4",
    "BAGE5",
    "BCL11B",
    "BCL3",
    "BCL7A",
    "BCR",
    "BIRC3",
    "BMPR1A",
    "BRCA2",
    "BRD3",
    "BRIP1",
    "CALR",
    "CANT1",
    "CBL",
    "CBLC",
    "CBX4",
    "CCDC6",
    "CCND1",
    "CCND2",
    "CCNE1",
    "CD274",
    "CD79B",
    "CDK2",
    "CDK4",
    "CDK6",
    "CDKN1A",
    "CDKN1B",
    "CDKN2A",
    "CDKN2B",
    "CEBPA",
    "CHI3L1",
    "CHIC2",
    "CLP1",
    "CLTC",
    "CLTCL1",
    "CNBP",
    "CNOT3",
    "CNTRL",
    "CREB3L2",
    "DDIT3",
    "DDX10",
    "DDX6",
    "DEPTOR",
    "DICER1",
    "DNM2",
    "DNMT3A",
    "E2F1",
    "EED",
    "EIF4A2",
    "ELAVL2",
    "ELF4",
    "ELK4",
    "ERBB3",
    "ERC1",
    "ETV1",
    "ETV5",
    "ETV6",
    "EXT1",
    "FANCC",
    "FANCD2",
    "FANCG",
    "FAS",
    "FCGR2B",
    "FGFR2",
    "FH",
    "FIP1L1",
    "FNBP1",
    "FOXL2",
    "FOXO3",
    "FOXO4",
    "FSTL3",
    "FZD1",
    "GATA1",
    "GATA2",
    "GATA3",
    "GIMAP8",
    "GMPS",
    "GNA11",
    "GNAQ",
    "GPC3",
    "GRB2",
    "GUSB",
    "H3F3A",
    "H3F3B",
    "HIP1",
    "HMGA2",
    "HNF1A",
    "HOXA11",
    "HOXA13",
    "HOXA4",
    "HOXA5",
    "HOXA7",
    "HOXC11",
    "HOXC13",
    "HRAS",
    "HSP90AA1",
    "HSP90AB1",
    "IFNA1",
    "IFNA14",
    "IFNA2",
    "IFNA4",
    "IFNA6",
    "IFNA7",
    "IFNA8",
    "IFNB1",
    "IFNW1",
    "IKZF1",
    "JAK1",
    "JAK2",
    "JAZF1",
    "KDM5C",
    "KIAA1549",
    "KLF6",
    "KMT2A",
    "KRAS",
    "LANCL2",
    "LMO2",
    "LRIG3",
    "LYL1",
    "MALAT1",
    "MAML2",
    "MAP2K2",
    "MAPK1",
    "MDM4",
    "MEN1",
    "MET",
    "MGAM",
    "MIR200C",
    "MLF1",
    "MLLT1",
    "MLLT10",
    "MLLT3",
    "MNX1",
    "MSI2",
    "MTAP",
    "MTCP1",
    "MUC1",
    "MUC20",
    "MYC",
    "MYCN",
    "NACA",
    "NCOA1",
    "NDRG1",
    "NFIB",
    "NFKB2",
    "NONO",
    "NOTCH1",
    "NR1H2",
    "NR2E1",
    "NR4A3",
    "NRAS",
    "NRCAM",
    "NT5C2",
    "NUMA1",
    "NUP214",
    "NUTM2A",
    "OR2Z1",
    "PAFAH1B2",
    "PAX7",
    "PBX1",
    "PCSK7",
    "PDCD1LG2",
    "PDGFA",
    "PDPK1",
    "PHF6",
    "PIK3C2B",
    "PKM",
    "PMEL",
    "PMS2",
    "POT1",
    "POTED",
    "POU2AF1",
    "PPARG",
    "PPP2R1A",
    "PRCC",
    "PRDM16",
    "PRH1",
    "PRKAR1A",
    "PRKCA",
    "PRKCG",
    "PRKCI",
    "PRKCZ",
    "PRR4",
    "PRRX1",
    "PSIP1",
    "RAC1",
    "RAD21",
    "RAF1",
    "RALGDS",
    "RASA3",
    "RECQL4",
    "RELA",
    "RHOH",
    "RNF213",
    "RNF43",
    "RPN1",
    "RPS6KA4",
    "RPS6KB1",
    "SBDS",
    "SDHC",
    "SDHD",
    "SEC61G",
    "SEPT14",
    "SEPT5",
    "SEPT9",
    "SERPINE1",
    "SET",
    "SF3B6",
    "SH3GL1",
    "SMARCA4",
    "SMO",
    "SOX2",
    "SPRY2",
    "SRGAP3",
    "SRSF3",
    "SSX2",
    "STIL",
    "STK11",
    "SUFU",
    "SYK",
    "TAL2",
    "TARP",
    "TBL1XR1",
    "TCF3",
    "TCL1A",
    "TCL6",
    "TFEB",
    "TFG",
    "TFPT",
    "TFRC",
    "TLX1",
    "TNFRSF14",
    "TPM4",
    "TSC1",
    "VHL",
    "VTI1A",
    "WHSC1",
    "WT1",
    "WWTR1",
    "XPA",
    "XPC",
    "ZBTB16",
    "ZEB1",
    "ZNF331",
    "ZNF384",
    "ZNF713",
    "ACKR3",
    "ACSL3",
    "ACSL6",
    "AFF4",
    "ALDH2",
    "ARAF",
    "ARID2",
    "ATIC",
    "ATP1A1",
    "AXIN1",
    "BCL10",
    "BCL9",
    "BTG1",
    "BUB1B",
    "CARS",
    "CASC5",
    "CASP8",
    "CBFA2T3",
    "CCNB1IP1",
    "CD74",
    "CDH11",
    "CDX2",
    "CHN1",
    "CREB1",
    "CREB3L1",
    "CRLF2",
    "DUSP22",
    "EBF1",
    "EP300",
    "ERCC2",
    "ERRFI1",
    "EXT2",
    "FANCA",
    "FANK1",
    "FEV",
    "FGFR1OP",
    "FN1",
    "FOXO1",
    "FRG1",
    "FUBP1",
    "FUS",
    "GAS7",
    "GDF2",
    "GOLGA5",
    "GOPC",
    "GPHN",
    "GYS1",
    "HEATR4",
    "HERPUD1",
    "HIF1A",
    "HIST1H3B",
    "HMGN2P46",
    "HOXD11",
    "HOXD13",
    "IL21R",
    "ITK",
    "JUN",
    "KDM6A",
    "KLK2",
    "KTN1",
    "LCP1",
    "LHFP",
    "LMO1",
    "MAFB",
    "MAP2K4",
    "MAPK3",
    "MGMT",
    "MKL1",
    "MLST8",
    "MYCL",
    "NCKIPSD",
    "NCOA4",
    "NFE2L2",
    "NFKB1",
    "NOTCH2NL",
    "NPM1",
    "NRXN3",
    "NSD1",
    "NTRK3",
    "NUP98",
    "NUTM1",
    "OR4K1",
    "OR4K2",
    "OR4M1",
    "OR52N5",
    "P2RY8",
    "PALB2",
    "PATZ1",
    "PER1",
    "PHF21A",
    "PHOX2B",
    "PIK3CD",
    "POTEB",
    "PRF1",
    "PRKCB",
    "PRKCH",
    "RAD51B",
    "RBM15",
    "ROS1",
    "RPS6KA5",
    "SEC22B",
    "SH2B3",
    "SPECC1",
    "SSX1",
    "SSX4",
    "TAF15",
    "TAL1",
    "TCF7L2",
    "TERT",
    "TET1",
    "TFE3",
    "TLX3",
    "TNFAIP3",
    "TRAF7",
    "TRIM33",
    "TRIP11",
    "TSC2",
    "TSHR",
    "TTL",
    "WAS",
    "WWOX",
    "YWHAE",
    "ZMYM2"
  ];

  // pointColor: DataField = DataFieldFactory.getUndefined();
  // pointShape: DataField = DataFieldFactory.getUndefined();
  // pointSize: DataField = DataFieldFactory.getUndefined();
  pointIntersect: DataField = DataFieldFactory.getUndefined();
  database: string;

  constructor() {
    this.database = GraphConfig.database;
  }
>>>>>>> a947a94743ca0203655e535e63bac428d1227be3
}
